apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wi41zfxjo-go
  janus-idp.io/tekton: wi41zfxjo-go
  backstage.io/kubernetes-id: wi41zfxjo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wi41zfxjo-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
