apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wi41zfxjo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wi41zfxjo-go 
  name: wi41zfxjo-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wi41zfxjo-go 
