apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wi41zfxjo-go-gitops
  description: This is GitOps manifest for wi41zfxjo-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: wi41zfxjo-go
    janus-idp.io/tekton: wi41zfxjo-go 
    backstage.io/kubernetes-id: wi41zfxjo-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:wi41zfxjo-go
